In [414]:
using DataFrames, DataFramesMeta
using Printf
using LinearAlgebra
using CSV

List files in the data directory:

In [4]:
readdir("../data")

3-element Array{String,1}:
 "winemag-data-130k-v2.csv"  
 "winemag-data-130k-v2.json" 
 "winemag-data_first150k.csv"

Lets check the last file ("winemag-data_first150k.csv")

In [5]:
df = CSV.read("../data/winemag-data_first150k.csv")
df[1:5,:]

5×11 DataFrame. Omitted printing of 9 columns
│ Row │ Column1 │ country │
│     │ Int64⍰  │ String⍰ │
├─────┼─────────┼─────────┤
│ 1   │ 0       │ US      │
│ 2   │ 1       │ Spain   │
│ 3   │ 2       │ US      │
│ 4   │ 3       │ US      │
│ 5   │ 4       │ France  │

**Lets see the headers we have available:**

In [6]:
print(names(df))

Symbol[:Column1, :country, :description, :designation, :points, :price, :province, :region_1, :region_2, :variety, :winery]

In [7]:
nrows, ncols = size(df)
for row in 1:nrows
    for col in 7
        if ismissing(df[row,col])
            println("$(names(df)[col]) value for $(row) is missing!")
        end
    end
end

province value for 1134 is missing!
province value for 1441 is missing!
province value for 68227 is missing!
province value for 113017 is missing!
province value for 135697 is missing!


In [8]:
deleterows!(df, [1134, 1441, 68227, 113017, 135697]);

150925×11 DataFrame. Omitted printing of 9 columns
│ Row    │ Column1 │ country │
│        │ Int64⍰  │ String⍰ │
├────────┼─────────┼─────────┤
│ 1      │ 0       │ US      │
│ 2      │ 1       │ Spain   │
│ 3      │ 2       │ US      │
│ 4      │ 3       │ US      │
│ 5      │ 4       │ France  │
│ 6      │ 5       │ Spain   │
│ 7      │ 6       │ Spain   │
│ 8      │ 7       │ Spain   │
│ 9      │ 8       │ US      │
│ 10     │ 9       │ US      │
⋮
│ 150915 │ 150919  │ France  │
│ 150916 │ 150920  │ Italy   │
│ 150917 │ 150921  │ France  │
│ 150918 │ 150922  │ Italy   │
│ 150919 │ 150923  │ France  │
│ 150920 │ 150924  │ France  │
│ 150921 │ 150925  │ Italy   │
│ 150922 │ 150926  │ France  │
│ 150923 │ 150927  │ Italy   │
│ 150924 │ 150928  │ France  │
│ 150925 │ 150929  │ Italy   │

**Lets reduce the size of the dataset to wines in Oregon (mostly because I'm running out of time doing this)**

In [252]:
@linq oregon = df |>
where(:province .== "Oregon")

4589×11 DataFrame. Omitted printing of 9 columns
│ Row  │ Column1 │ country │
│      │ Int64⍰  │ String⍰ │
├──────┼─────────┼─────────┤
│ 1    │ 3       │ US      │
│ 2    │ 8       │ US      │
│ 3    │ 11      │ US      │
│ 4    │ 12      │ US      │
│ 5    │ 14      │ US      │
│ 6    │ 15      │ US      │
│ 7    │ 26      │ US      │
│ 8    │ 27      │ US      │
│ 9    │ 68      │ US      │
│ 10   │ 73      │ US      │
⋮
│ 4579 │ 149896  │ US      │
│ 4580 │ 149897  │ US      │
│ 4581 │ 149963  │ US      │
│ 4582 │ 150028  │ US      │
│ 4583 │ 150068  │ US      │
│ 4584 │ 150081  │ US      │
│ 4585 │ 150135  │ US      │
│ 4586 │ 150185  │ US      │
│ 4587 │ 150252  │ US      │
│ 4588 │ 150327  │ US      │
│ 4589 │ 150372  │ US      │

In [415]:
varieties = unique(oregon[:variety])
wineries = unique(oregon[:winery])

n_varieties = length(varieties)
n_wineries = length(wineries)
@printf("The number of wines rated in Oregon: %d\n", size(oregon,1))
@printf("The number of wineries rated in Oregon: %d\n", n_wineries)
@printf("The number of different variety of wines in Oregon: %d\n", n_varieties)

The number of wines rated in Oregon: 4589
The number of wineries rated in Oregon: 371
The number of different variety of wines in Oregon: 67


# Making our data matrix

In [417]:
A = zeros(Float64, n_varieties,n_wineries)
x = 0
for i = 1:n_varieties
    for u = 1:n_wineries
        @linq this_winery = oregon |> where(:winery .== wineries[u])
        @linq this_wineries_wine = this_winery |> where(:variety .== varieties[i])
        n_wines = nrow(this_wineries_wine)
        if n_wines > 0
            A[i, u] = sum(this_wineries_wine[:points])/n_wines
        else
            A[i, u] = -1
        end
    end
end
A

67×371 Array{Float64,2}:
 91.2857  92.1739  93.5714  91.1905  …  87.0  88.0  -1.0  -1.0  -1.0  85.0
 91.3125  94.4286  -1.0     91.3571     -1.0  -1.0  -1.0  -1.0  90.0  -1.0
 89.8333  -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0     …  -1.0  -1.0  -1.0  82.5  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 -1.0     -1.0     -1.0     -1.0     …  -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 89.6     -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0
 88.3333  -1.0     -1.0     -1.0        -1.0  -1.0  -1.0  -1.0  -1.0  -1.0


# Lets find the fraction of values against missing values

In [12]:
sum(A .> -1)/length(A)

0.038902522428289815

In [257]:
threshold = 4

skip_columns = falses(n_wineries)
for col = 1:n_wineries
    n_not_missing = sum(A[:, col] .> -1)
    if n_not_missing > threshold
        skip_columns[col] = true
    end
end

skip_rows = falses(n_varieties)
for row = 1:n_varieties
    n_not_missing = sum(A[row, :] .> -1)
    if n_not_missing > threshold
        skip_rows[row] = true
    end
end

In [258]:
println(sum(skip_columns))
println(sum(skip_rows))

48
24


In [418]:
data_matrix = A[skip_rows, skip_columns]
OG = deepcopy(data_matrix)
mask = data_matrix .> 0
avg_rating = sum(data_matrix[mask])/length(data_matrix[mask])
data_matrix[mask] = data_matrix[mask] .- avg_rating
data_matrix

24×48 Array{Float64,2}:
  4.0649   -1.0       -1.0       -0.99004   …  -1.0       -5.22081   -2.97081
  4.09169   0.279191  -1.0       -1.0          -1.0       -1.0       -5.22081
  2.61252  -1.0       -1.0       -1.36367      -1.0       -4.22081   -4.22081
 -1.0      -1.0       -1.0       -1.22081      -1.0       -1.0       -3.22081
 -1.0      -1.0       -1.0       -1.0          -1.0       -1.0       -1.0    
 -1.0      -1.0       -1.0       -1.0       …  -1.0       -1.0       -1.0    
 -1.0      -0.220809   1.77919   -2.22081      -1.0        0.779191  -4.22081
 -1.0      -1.0       -1.0       -1.0          -1.0       -1.0       -4.22081
 -1.0      -1.0        0.779191   0.779191     -1.0       -1.0       -1.0    
  2.37919  -6.22081   -1.0       -1.0          -1.0       -1.0       -3.22081
  1.11252  -1.0       -1.0       -1.0       …  -1.0       -1.0       -1.0    
 -1.0      -1.0       -1.0       -1.0          -1.0       -6.22081   -1.0    
 -1.0      -1.0       -0.220809  -1.0   

In [419]:
sum(data_matrix .> -1)/length(data_matrix)

0.15625

In [431]:
function SGD(X::Array{Float64, 2}, k::Int64, γ::Float64, n_epoch::Int64)
    n_variety, n_winery = size(X)
    p = rand(n_variety, k) .* 0.2 .- 0.1
    q = rand(n_winery, k) .* 0.2 .- 0.1
    
    for ep = 1:n_epoch
        for i = 1:n_variety
            for j = 1:n_winery
                if X[i,j] < 0
                    continue
                end
                err = X[i,j] - dot(p[i, :], q[j, :])
                q_ = err * q[j, :]
                p_ = err * p[i, :]
                p[i, :] += γ * q_
                q[j, :] += γ * p_
            end
        end
    end
    return p, q
end

SGD (generic function with 1 method)

In [432]:
p, q = SGD(data_matrix, 10, 0.01, 100)

([0.816621 -0.418353 … 0.073985 0.593846; 0.255447 0.10275 … 0.0179691 0.328851; … ; 1.34412 -0.461248 … 0.894955 -0.28936; 1.32862 -0.646737 … 0.836486 -0.400612], [0.466949 -0.0867776 … -0.232825 -0.00341132; 0.14248 -0.0242611 … -0.0206372 0.0377417; … ; 0.126504 -0.119769 … 0.0133615 0.0662394; 0.0281446 -0.02607 … -0.00785101 0.0707364])

In [433]:
function estimate(wine, variety)
    @printf("Winery: %s\nVariety: %s\n", wineries[wine], varieties[variety])
    return dot(p[wine], q[variety]) + avg_rating
end

estimate (generic function with 1 method)

In [434]:
estimate(5, 3)

Winery: Panther Creek
Variety: Pinot Gris


87.12024249848974

In [436]:
new_ratings = p*q'
rmse = sqrt(sum((data_matrix[mask].-new_ratings[mask]).^2)/length(data_matrix))
@printf("Root Mean Squared Error: %f\n", rmse)

Root Mean Squared Error: 1.120706


In [360]:
function SGD_regularized(X::Array{Float64, 2}, k::Int64, γ::Float64, n_epoch::Int64, λ::Float64)
    n_variety, n_winery = size(X)
    p = rand(n_variety, k) .* 2 .- 1
    q = rand(n_winery, k) .* 2 .- 1
    
    for ep = 1:n_epoch
        for i = 1:n_variety
            for j = 1:n_winery
                if X[i,j] < 0
                    continue
                end
                err = X[i,j] - dot(p[i, :], q[j, :])
                q_ = err * q[j, :]
                p_ = err * p[i, :]
                p[i, :] += γ * (q_ - λ .* p[i, :])
                q[j, :] += γ * (p_ - λ .* q[j, :])
            end
        end
    end
    return p, q
end

SGD_regularized (generic function with 1 method)

In [427]:
p, q = SGD_regularized(data_matrix, 10, 0.01, 1000, 0.02)

([-0.246461 0.617844 … -0.432837 -0.115429; -0.0289538 -0.178223 … -0.476018 -0.305676; … ; -1.13563 0.624995 … -0.844984 -0.304396; -0.883505 1.84268 … -0.354454 -0.666433], [-0.532737 -0.222233 … -0.647947 -0.504887; -0.179209 0.560603 … 0.414415 -0.217158; … ; 0.558224 0.256096 … 0.235618 0.266347; -0.880881 0.403641 … 0.730178 -0.611976])

In [437]:
new_ratings_regularized = p*q'
rmse_regularized = sqrt(sum((data_matrix[mask].-new_ratings_regularized[mask]).^2)/length(data_matrix))
@printf("Root Mean Squared Error for regularized model: %f\n", rmse_regularized)

Root Mean Squared Error for regularized model: 1.120706


In [429]:
new_ratings_regularized .+ average_rating

24×48 Array{Float64,2}:
 91.3913  87.0707  89.2168  86.8622  …  88.4693  86.9373  89.3271  88.6013
 91.3178  87.5966  87.5279  86.4009     89.0724  86.6607  88.0337  88.4641
 90.0644  87.7838  88.8643  85.6786     88.1227  87.6614  88.1705  89.7892
 86.2496  87.6029  87.2003  88.241      87.7114  89.1274  88.2716  85.6729
 88.087   87.3035  88.7185  87.1119     85.7461  87.0139  88.1814  87.8346
 89.31    87.0693  88.2289  87.0145  …  88.3553  86.8764  88.2332  87.2754
 89.1148  86.3302  89.2465  88.4918     86.6484  84.7548  88.2474  87.6477
 88.1893  86.5168  88.8003  87.3084     87.8197  84.8569  87.2536  88.7284
 88.3528  86.6167  88.0275  88.0205     86.9521  85.655   87.6899  87.5284
 90.1268  89.0414  88.4873  86.8238     89.3019  88.3309  89.4775  88.8896
 88.2417  86.5928  87.9251  87.113   …  86.9167  86.5113  87.4308  87.6678
 88.2384  87.5754  88.7023  86.6849     87.2517  87.92    88.2487  87.2741
 88.2151  86.6199  88.2916  87.8787     87.0143  86.1644  87.926   86.0008
 

In [430]:
new_ratings .+ average_rating

24×48 Array{Float64,2}:
 91.5542  87.7967  90.7919  88.0734  …  87.3681  87.3663  87.6469  87.4399
 91.0967  87.6065  89.8539  87.5971     87.2649  87.443   87.2288  87.5075
 90.3383  87.6112  89.2179  88.008      87.4319  87.5074  87.6203  87.6317
 87.5165  87.3701  87.3594  87.41       87.3865  87.3834  87.3842  87.3887
 87.7595  87.3748  87.7396  87.4331     87.3562  87.3657  87.4389  87.3771
 89.2444  87.5476  88.4756  87.6983  …  87.3941  87.525   87.4791  87.5394
 89.5327  87.7524  89.2428  88.6675     87.4726  87.4926  88.2513  87.5384
 90.0703  87.8217  90.1801  87.4714     87.4026  87.5431  87.3511  87.5246
 88.0794  87.4326  88.0706  87.8788     87.2834  87.257   87.6413  87.2359
 90.2513  88.0934  89.7523  88.1077     87.6415  87.9734  87.8807  87.7955
 88.2559  87.2415  88.0355  87.695   …  87.136   87.1222  87.4601  87.117 
 88.8625  87.4242  89.211   87.937      87.1656  87.1991  87.6649  87.195 
 89.0748  87.5885  88.7587  87.8583     87.3914  87.4131  87.668   87.496 
 